name: 🚀 Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: 22
          script: |
            cd /root/xo
            git pull
            npm install --legacy-peer-deps
            npm run build
            cp -r ./build/* /var/www/xo/
            chown -R www-data:www-data /var/www/xo
            systemctl reload nginx
